package com.ssxt.web.vo;
// Generated 2016-8-22 15:31:25 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * SymModules generated by hbm2java
 */
public class SymModulesVo implements java.io.Serializable {

	private Long id;
	private Long parentID;
	private String sysName;
	private String moduleName;
	private String resourceType;
	private String operateType;
	private String link;
	private String remark;
	private Integer uiseq;
	private String requestMethod;
	 

	public SymModulesVo() {
	}


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public Long getParentID() {
		return parentID;
	}


	public void setParentID(Long parentID) {
		this.parentID = parentID;
	}


	public String getSysName() {
		return sysName;
	}


	public void setSysName(String sysName) {
		this.sysName = sysName;
	}


	public String getModuleName() {
		return moduleName;
	}


	public void setModuleName(String moduleName) {
		this.moduleName = moduleName;
	}


	public String getResourceType() {
		return resourceType;
	}


	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}


	public String getOperateType() {
		return operateType;
	}


	public void setOperateType(String operateType) {
		this.operateType = operateType;
	}


	public String getLink() {
		return link;
	}


	public void setLink(String link) {
		this.link = link;
	}


	public String getRemark() {
		return remark;
	}


	public void setRemark(String remark) {
		this.remark = remark;
	}


	public Integer getUiseq() {
		return uiseq;
	}


	public void setUiseq(Integer uiseq) {
		this.uiseq = uiseq;
	}


	public String getRequestMethod() {
		return requestMethod;
	}


	public void setRequestMethod(String requestMethod) {
		this.requestMethod = requestMethod;
	}
 
}
